spring.datasource:
  url: jdbc:h2:mem:citiesdb
  driverClassName: org.h2.Driver
  username: sa
  password: 
 
spring.jpa:
  show-sql: true
  properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  hibernate.ddl-auto: none

spring.h2.console:
  enabled: true
  # default path: h2-console
  path: /h2-ui

server.port: ${APP_PORT:8080}